# Generated by Django 3.1.3 on 2020-11-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
